### PR TITLE
Mac mini 2018 i7 16 512

### PR DESCRIPTION
**Pull request by Kuluum**
Mac Mini 2018, i7 3.2 GHz 6-core, 16 RAM, 512 SSD, XCode 11.7, macos 10.15.5  ->    300 sec

### CODE REVIEW

**Comment by Kuluum** [comment]
Screenshot 2020-09-14 at 10 16 12

**Comment by devMEremenko** [comment]
Hi @Kuluum, 

Thank you for your contribution.

Could you please add a link to the end of the [Contributors](https://github.com/devMEremenko/XcodeBenchmark#contributors) list?

**Comment by Kuluum** [comment]
@devMEremenko done

**Comment by devMEremenko** [comment]
Thank you

**Pull request merged**
