### PR TITLE
Sort & Add MacBook Pro 15" 2014 i7 using Xcode 12.2

### PR DESCRIPTION
**Pull request by vitalii-tab**
## Checklist

**If you have any non-Apple hardware components - submit your results to the `Custom Hardware` table.**

* [x] I performed [all steps](https://github.com/devMEremenko/XcodeBenchmark#before-each-test) to correctly run XcodeBenchmark.
* [x] I attached a screenshot with a compilation time and other fields, [example](img/contribution-example.png).
* [x] I confirm that `Time` column is still sorted.
* [x] I am added to the end of the [Contributors](https://github.com/devMEremenko/XcodeBenchmark#contributors) list.
* [x] The content in cells is centered. You can use [this tool](https://www.tablesgenerator.com/markdown_tables) to edit a table.
    - File -> Paste table data
    - Select all cells -> Right click -> Text align -> Center
image

### CODE REVIEW

**Comment by devMEremenko** [comment]
Hi @vitallii-t,

Thank you for your contribution

Could you please attach a screenshot for the following device
-  MacBook Pro 15" 2014 

Thanks

**Comment by vitallii-t** [comment]
Hi @devMEremenko 
Do you mean a screenshot of "About this mac"? 
I've sorted rows to follow your checklist, that is why I have more addition and deletion.

**Comment by vitallii-t** [comment]
It's already sorted. I'm deleting sort commit

**Comment by devMEremenko** [comment]
You are right, everything is correct

**Pull request merged**
