### PR TITLE
MacBook M1 test run

### PR DESCRIPTION
**Pull request by sverrisson**
## Checklist

**If you have any non-Apple hardware components - submit your results to the `Custom Hardware` table.**

* [x] I performed [all steps](https://github.com/devMEremenko/XcodeBenchmark#before-each-test) to correctly run XcodeBenchmark.
* [x] I attached a screenshot with a compilation time and other fields, [example](img/contribution-example.png).
* [x ] I confirm that `Time` column is still sorted.
* [x] I am added to the end of the [Contributors](https://github.com/devMEremenko/XcodeBenchmark#contributors) list.
* [x] The content in cells is centered. You can use [this tool](https://www.tablesgenerator.com/markdown_tables) to edit a table.
    - File -> Paste table data
    - Select all cells -> Right click -> Text align -> Center
MacBook M1

### CODE REVIEW

**Comment by devMEremenko** [comment]
Hi @sverrisson,

I am sorry for the late response, merged 👍

**Comment by devMEremenko** [comment]
@sverrisson, by the way, do you still like M1 after two months of usage? Any unexpected errors/incompatible apps that you cannot resolve?

**Comment by sverrisson** [comment]
> @sverrisson, by the way, do you still like M1 after two months of usage? Any unexpected errors/incompatible apps that you cannot resolve?

@devMEremenko I am still waiting for AndroidStudio to be updated and to be able to write Flutter Apps. I installed Parallels test version and am running Windows on ARM there. So, far it's been good although I experienced problem with updating Xcode and the process hung from the Appstore. I just use this as a second computer to get away from the desk, so the main feature I like is to just use it without worrying about charging for weeks.

**Comment by devMEremenko** [comment]
@sverrisson, thanks, then it's better to wait for MBP 16
- Most of the common apps/tools will support M1
- Apple will fix more bugs in macOS. Probably, on the hardware level too.
- 16" screen is still a bit more useful than a 13" one. Especially away from the desk

**Pull request merged**
