### PR TITLE
Run in terminal

### PR DESCRIPTION
**Pull request by sverrisson**
I did some experimentation by running the Xcode compilation in the Terminal with a script that prepares and deletes the DerivedData folder and chooses the correct scene, etc. Hopefully this would prevent the issues of users following instructions incorrectly and reduce human influence in the tests. 
Please try it out and tell me what you think. There is a lot of printout coming, but the test should be consistent at least.

### CODE REVIEW

**Comment by devMEremenko** [comment]
Hi @sverrisson,

Thank you for suggesting this, I like the idea.

I ran the script several times and received different results

1.
real: 7m 23s
user: 0m 16s
sys: 0m 4s

2. 
real: 6m 52s
user: 0m 16s
sys: 0m 4s

3.
real: 7m 0s
user: 0m 16s
sys: 0m 4s

However, when I compile manually I receive a solid result *every time* - 440s - 7m 20s (+-2 sec)

I tested on MacBook Pro 2018 (i7, 512 SDD,16 RAM) and MacBook Pro 2015 (i7, 512 SDD,16 RAM)

Could you run the script several times on your machine?

**Comment by sverrisson** [comment]
Hi @devMEremenko 
These are my results:

1) 
real	4m14.770s
user	0m15.006s
sys	0m4.359s

2)
real	4m16.526s
user	0m14.549s
sys	0m4.027s

3) 
real	4m15.553s
user	0m13.821s
sys	0m4.138s

Thus, average 255.6 s

Running manually I see similar variance. But first when I ran manually I forgot to change the scheme, etc. and thus was experiencing wrong results.

I fixed the instructions and added a script for writing out the main parameters of the computer running on:
`    Hardware Overview:

      Model Name: iMac
      Model Identifier: iMac19,1
      Processor Name: 8-Core Intel Core i9
      Processor Speed: 3,6 GHz
      Number of Processors: 1
      Total Number of Cores: 8
      L2 Cache (per Core): 256 KB
      L3 Cache: 16 MB
      Hyper-Threading Technology: Enabled
      Memory: 64 GB
      Boot ROM Version: 1037.140.50.0.0
      SMC Version (system): 2.46f12`

We could add this as a second column for running the benchmark as it would prevent the *wrong* results that have been submitted.

**Comment by igorkulman** [comment]
Looking at the script, deleting the whole derived data folder seems like an overkill. Instead you can specify a custom derived data folder for `xcodebuild` with `-derivedDataPath` and just delete that.

**Comment by devMEremenko** [comment]
Hi @sverrisson,

I am sorry for the late response.

I've just updated XcodeBenchmark to support Xcode `12.0` and added a script to run in Terminal based on your approach.

Could you please check the following [pull request](https://github.com/devMEremenko/XcodeBenchmark/pull/27/files)?
It would be great if you can compile the project using Xcode `12.2` (I cannot currently update to this version).

Thank you

**Comment by sverrisson** [comment]
> Hi @sverrisson,
> 
> I am sorry for the late response.
> 
> I've just updated XcodeBenchmark to support Xcode `12.0` and added a script to run in Terminal based on your approach.
> Here is an [example of results](https://github.com/devMEremenko/XcodeBenchmark/blob/bb8a66bce361be4d60157ecd61aedad015b6cc2d/img/contribution-example.png).
> 
> Could you please check the following [pull request](https://github.com/devMEremenko/XcodeBenchmark/pull/27/files)?
> It would be great if you can compile the project using Xcode `12.2` (I cannot currently update to this version).
> 
> Thank you

**Comment by sverrisson** [comment]
Hi @devMEremenko,
I have finished testing and made some updates and changes, i.e. used derived folder as suggested above. I cant commit them to your pull request as I don't have write access to this project.  I can create a separate PR or you give me access. Just let me know.

**Comment by devMEremenko** [comment]
Hi @sverrisson,

I've sent you an invitation to become a collaborator

**Comment by devMEremenko** [comment]
Concerning the derived data path: 

I suggest discussing/implementing this in further pull requests.

**Comment by devMEremenko** [comment]
The final solution is accepted [there](https://github.com/devMEremenko/XcodeBenchmark/pull/32).

**Pull request closed without merging**
