### PR TITLE
Updated to use a seperate build folder

### PR DESCRIPTION
**Pull request by sverrisson**
Use a temporary derived folder for the running of the benchmark, which allows the actual Xcode folder to remain unaffected by these tests. This will reduce garbage for users and the derived folder is deleted after the run.

### CODE REVIEW

**Comment by devMEremenko** [comment]
Hi @sverrisson,

Let's merge this PR once we receive results for all of the devices that run on Apple M1 (to ensure equal conditions for all devices).

**Comment by sverrisson** [comment]
> Hi @sverrisson,
> 
> Let's merge this PR once we receive results for all of the devices that run on Apple M1 (to ensure equal conditions for all devices).

OK, we should wait.  But I tested it and the running time did not change between them, as both start from a fresh folder.

**Comment by igor-makarov** [comment]
Hi @devMEremenko - could this be merged? It shouldn't affect performance and all of the M1 laptops have been benchmarked.

**Comment by devMEremenko** [comment]
Hi @igor-makarov, @sverrisson,

That's finally merged.

**Pull request merged**
