### PR TITLE
Add My Result

### PR DESCRIPTION
**Pull request by mlch911**
## Checklist

**If you have any non-Apple hardware components - submit your results to the `Custom Hardware` table.**

* [x] I performed [all steps](https://github.com/devMEremenko/XcodeBenchmark#before-each-test) to correctly run XcodeBenchmark.
* [x] I attached a screenshot with a compilation time and other fields, [screenshot](https://i.loli.net/2020/11/24/tmL9gz2h1yb7caZ.png).
* [x] I confirm that `Time` column is still sorted.
* [x] I am added to the end of the [Contributors](https://github.com/devMEremenko/XcodeBenchmark#contributors) list.
* [x] The content in cells is centered. You can use [this tool](https://www.tablesgenerator.com/markdown_tables) to edit a table.
    - File -> Paste table data
    - Select all cells -> Right click -> Text align -> Center

screenshot

### CODE REVIEW

**Comment by devMEremenko** [comment]
Hi @mlch911,

Could you please attach a screenshot according to:

>  I attached a screenshot with a compilation time and other fields

**Comment by mlch911** [comment]
> Hi @mlch911,
> 
> Could you please attach a screenshot according to:
> 
> > I attached a screenshot with a compilation time and other fields

sorry about this mistake

**Comment by githubbrightgrove** [comment]
Hi @mlch911,

I am sorry for the late response. 

A screenshot can be attached directly to this conversation. Here is [an example](https://github.com/devMEremenko/XcodeBenchmark/pull/93)

**Comment by devMEremenko** [comment]
Hi @mlch911,

I am sorry for the late response. 

A screenshot can be attached directly to this conversation. Here is [an example](https://github.com/devMEremenko/XcodeBenchmark/pull/93)

**Comment by mlch911** [comment]
> Hi @mlch911,
> 
> I am sorry for the late response.
> 
> A screenshot can be attached directly to this conversation. Here is [an example](https://github.com/devMEremenko/XcodeBenchmark/pull/93)

I added it in that link last time. Added image this time.

**Comment by devMEremenko** [comment]
@mlch911, thanks, merged

**Pull request merged**
