### PR TITLE
Adds benchmark for MacBook Pro 13" 2020

### PR DESCRIPTION
**Pull request by iOSleep**

### CODE REVIEW

**Comment by devMEremenko** [comment]
Hi @iOSleep,

Thank you for your efforts.

XcodeBenchmark has been just updated to support Xcode 12 and running from `Terminal` (see updated [ReadMe](https://github.com/devMEremenko/XcodeBenchmark))

Could you please rerun your tests with the latest version of XcodeBenchmark and ensure you attached all necessary information described in the [Contribution](https://github.com/devMEremenko/XcodeBenchmark#contribution) section.

Thanks

**Comment by iOSleep** [comment]
Hi @devMEremenko ,
Finished all things
QQ20201119-120243@2x

**Comment by azonov** [comment]
@iOSleep are you sure what you would like to avoid your profile from the contributors list? It's necessary to commit by yourself.

**Comment by iOSleep** [comment]
@azonov oh thanks, I always forget it 🤣

**Comment by devMEremenko** [comment]
Thanks for the update, @iOSleep

**Pull request merged**
