### PR TITLE
M1 MBP 13" Benchmark Results

### PR DESCRIPTION
**Pull request by soorinpark**
## Checklist

* [x] I performed [all steps](https://github.com/devMEremenko/XcodeBenchmark#before-each-test) to correctly run XcodeBenchmark.
* [x] I attached a screenshot with a compilation time and other fields, [example](img/contribution-example.png).
* [x] I confirm that `Time` column is still sorted in the [Score](https://github.com/devMEremenko/XcodeBenchmark#score) section.
* [x] I am added to the end of the [Contributors](https://github.com/devMEremenko/XcodeBenchmark#contributors) list.
* [x] The content in cells is centered. You can use [this tool](https://www.tablesgenerator.com/markdown_tables) to edit a table.
    - File -> Paste table data
    - Select all cells -> Right click -> Text align -> Center

Screen Shot 2020-11-17 at 11 44 07 AM

### CODE REVIEW

**Comment by devMEremenko** [comment]
Wow, much better than the desktop-class i9 in iMac 27" 👍

Thank you for your contribution.

Was it silent during the test? Did it become hot?

**Comment by soorinpark** [comment]
@devMEremenko It was silent and cool like a ninja <3 but in all seriousness I'm so impressed with this result

**Comment by devMEremenko** [comment]
Hi @soorinpark,

Can I ask you to perform the following commands in `Terminal` and share a result?

`system_profiler SPSerialATADataType`
`system_profiler SPHardwareDataType`

You can exclude a serial number, etc

1. I noticed that there is no information about SSD.
2. It might be a measurement error, but [MacBook Air (M1, 16 RAM)](https://github.com/devMEremenko/XcodeBenchmark/issues/44) runs a bit faster. Possibly, it will help to understand a reason.

**Comment by soorinpark** [comment]
@devMEremenko 

I just ran it again and got 119s haha
Screen Shot 2020-11-18 at 3 34 56 PM
`system_profiler SPSerialATADataType` did not output anything but ran `system_profiler SPStorageDataType` instead.
Screen Shot 2020-11-18 at 3 22 24 PM
Screen Shot 2020-11-18 at 3 23 24 PM

Also for fun I just ran the test with Rosetta 2:

Screen Shot 2020-11-18 at 3 14 56 PM
Screen Shot 2020-11-18 at 3 32 17 PM

**Comment by devMEremenko** [comment]
Thank you, I updated a result

**Pull request merged**
