### PR TITLE
Results from 15in MBP 2016 and Ryzen 5 3600 based Hackintosh

### PR DESCRIPTION
**Pull request by radianttap**
The result from my Ryzentosh is honestly staggering. I checked it twice and it holds up.

### CODE REVIEW

**Comment by sverrisson** [comment]
Did you remove the `DerivedData` folder before running?

**Comment by radianttap** [comment]
Yes, both times. Just ran it again, this time also running [AMD Power Gadget](https://github.com/trulyspinach/SMCAMDProcessor) to see what the core clocks are. 

With it, it finished in 164s.

**Comment by radianttap** [comment]
BTW, this is the [Ryzentosh hardware](https://github.com/radianttap/EFI-ASRock-X570-ITX-iMacPro1-1) I use.

**Comment by devMEremenko** [comment]
Thank you for contribution @radianttap

**Comment by devMEremenko** [comment]
Thank you for contribution @radianttap

**Comment by sverrisson** [comment]
@radianttap 
Could you run the BlackMagic Disk Speed Test on the Ryzentosh and screenshot the results here. [https://apps.apple.com/us/app/blackmagic-disk-speed-test/id425264550?mt=12](https://apps.apple.com/us/app/blackmagic-disk-speed-test/id425264550?mt=12)

**Comment by radianttap** [comment]
DiskSpeedTest-5GB

Here it is, 5GB stress test.

**Comment by sverrisson** [comment]
@radianttap then your numbers don't add up. Were you using Xcode 11.6 or Xcode 11.7?

**Comment by razvizion** [comment]
@radianttap There is something wrong in your build time. Even my 8-core 9th Gen @4.8GHz doesn't come close to this.

**Comment by radianttap** [comment]
Aargh, cr*p - I missed to set "Generic iOS Device" as target. This is embarassing 😳, thanks guys.
It's 312s, not 160s.
Will fix my branch so it can be re-merged.

**Comment by sverrisson** [comment]
@radianttap yes, the procedure is quite delicate and easy to miss this. :)

**Pull request merged**
