### PR TITLE
Add 2023 M2 Max MacBook Pro 16"

### PR DESCRIPTION
**Pull request by jCharv**
## Checklist

**If you have any non-Apple hardware components - submit your results to the `Custom Hardware` table.**

* [x] I performed [all steps](https://github.com/devMEremenko/XcodeBenchmark#before-each-test) to correctly run XcodeBenchmark.
* [x] I used Xcode 12.5 or above.
* [x] I attached a screenshot with a compilation time and other fields, [example](img/contribution-example.png).
* [x] I confirm that `Time` column is still sorted.
* [x] The content in cells is centered.

Screenshot 2023-01-26 at 15 34 31

### CODE REVIEW

**Comment by devMEremenko** [comment]
🚀

**Comment by lprhodes** [comment]
The review of the M2 Pro with 12 CPU cores have been showing around 82 seconds which is a fairly significant difference to the M2 Max you've reported (far more than I'd expect when the CPU's cores are meant to essentially be the same)  Did you have High Power mode on @jCharv?

**Comment by jCharv** [comment]
@lprhodes That first one might have been done on high power, can't remember exactly. Max has 2x faster unified memory than Pro, that might a reason for the difference. Anyway here is a run on battery in automatic mode:

Screenshot 2023-02-06 at 10 23 10

**Comment by lprhodes** [comment]
Thanks for that! Yeah the bandwidth speed definitely comes into play. I think the discrepancy may also be related to the Xcode versions reviewers are using too.

**Pull request merged**
